# Spring Boot configuration
spring:
  profiles:
    active: dev
  
  # Database configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://37.148.213.195:5432/emlakjet
    username: emlakjet
    password: emlakjet123
  
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none 
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  
  # Redis configuration
  redis:
    host: 172.17.0.4
    port: 6370
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 8
  cache:
    type: redis
    redis:
      time-to-live: 30
      cache-null-values: false

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug

# Server configuration
server:
  port: 8080